### ISSUE TITLE
EnableStashStatus = $true is closing PowerShell console

### ISSUE THREAD

**Issue by PiterGoCompany** [dahlbyk/posh-git#493] opened 2017-09-29 06:12 UTC
### System Details

- posh-git version/path: 0.7.1  C:\tools\poshgit\dahlbyk-posh-git-a4faccd\src
- PowerShell version: 5.1.15063.502
- Git version: 2.14.2.windows.1
- Operating system name and version: Microsoft Windows NT 10.0.15063.0

### Issue Description

After upgrading GIT to the 2.14.2.windows.1 version with enabled stash status, PowerShell console is closing while opening (in directories with git repo) without any error. I have found out that the problem is related with GitUtils.ps1 file and the line: `$stashCount = $null | git stash list 2>$null | measure-object | Select-Object -expand Count`. After replacing `git stash list` with any git command PowerShell starts without any problems.

**Comment by dahlbyk** [comment] 2017-09-29 07:44
Fascinating... What does that line give you when run by itself?

**Comment by PiterGoCompany** [comment] 2017-09-29 08:03
number of stashes in current git repo

**Comment by dahlbyk** [comment] 2017-09-29 18:51
If the command works outside the prompt, I have no idea why it would be crashing PowerShell. 🤔

**Comment by PiterGoCompany** [comment] 2017-10-02 05:27
The command in its exact form: `$stashCount = $null | git stash list 2>$null | measure-object | Select-Object -expand Count` isn't working. Works only `$null | git stash list | measure-object | Select-Object -expand Count` or `git stash list`.

**Comment by dahlbyk** [comment] 2017-10-02 05:34
Does it work with the `2>$null`? PowerShell literally just crashes when this code is hit?

**Comment by PiterGoCompany** [comment] 2017-10-02 05:50
While running poshgit script responsible for generating git statistics it doesn't work in any form. Outside poshgit it works as I said earlier (without `2>$null`)

**Comment by dahlbyk** [comment] 2017-10-02 19:18
Not sure what to tell you... @lzybkr any ideas?

**Comment by lzybkr** [comment] 2017-10-02 19:45
Doesn't sound familiar. Without more info, it is hard to diagnose, because that code runs in many, many different environments without any problems.

**Comment by PiterGoCompany** [comment] 2017-10-03 04:54
Problem starts to occur after upgrading git from 2.14.1. to 2.14.2. Earlier everything was OK. Maybe there is something with `git stash list` in the new version of git?

**Comment by dahlbyk** [comment] 2017-10-03 18:25
I wonder if it's from the `$null |`?

**Comment by PiterGoCompany** [comment] 2017-10-04 04:58
Removing `$null |?` doesn't help. Running `$stashCount = git stash list | measure-object | Select-Object -expand Count` from power shell console also works OK but the same line in GitUtils.ps1 file is causing Power Shell window close.

**Comment by dahlbyk** [comment] 2017-10-04 22:07
Grasping at straws here... try `$stashCount = $(git stash list) | measure-object | Select-Object -Expand Count`?

**Comment by rkeithhill** [comment] 2017-10-05 04:24
I think this is a bug in Git.  It crashes not only powershell but cmd as well `git stash list 2>nul` - kaboom!

**Comment by PiterGoCompany** [comment] 2017-10-05 04:56
@dahlbyk `$stashCount = $(git stash list) | measure-object | Select-Object -Expand Count` doesn't solve the problem, power shell still is closing.

**Comment by rkeithhill** [comment] 2017-10-05 05:05
As I mentioned above.  This is not specific to PowerShell.  This command crashes `CMD` as well.

**Comment by lzybkr** [comment] 2017-10-05 05:08
I think the bug is in cygwin-console-helper.exe. I noticed that cmd.exe and conhost.exe did not exit even though the window disappeared.

So then I tried running something after, like:

```
git stash list 2> $null; sleep -seconds 10; $pid > $env:TEMP\out
```

Then from another PowerShell window:

```
gc $env:TEMP\out | % { gps -id $_ }
```

So I see the process is still running correctly, just not visible.

I suspect `cygwin-console-helper.exe` because I stepped through in the debugger all of the process creation, and the window disappears shortly after this process spins up a new conhost - the process tree when this happens looks like:

```
8:046> |
   0	id: 45d0	create	name: cmd.exe
   1	id: 2fa4	child	name: git.exe
   2	id: 24a4	child	name: git.exe
   3	id: 4dd4	child	name: bash.exe
   4	id: 37dc	child	name: bash.exe
   5	id: 4ef8	child	name: bash.exe
   6	id: 4850	child	name: bash.exe
   7	id: 3b2c	child	name: bash.exe
.  8	id: 6798	exited	name: \\?\C:\Users\jason\Downloads\PortableGit\usr\bin\cygwin-console-helper.exe
   9	id: 2cf0	child	name: conhost.exe
```

**Comment by PiterGoCompany** [comment] 2017-10-05 05:16
@lzybkr I've checked my running processes list and there's a lot of powershell.exe

**Comment by lzybkr** [comment] 2017-10-05 05:26
I forgot to add - `cygwin-console-helper.exe` exists to hide the `conhost.exe` process that pops up, so it seems like it's just getting confused and hiding the wrong window.

I think it's reasonable to report a bug to cygwin. I looked very briefly and didn't find anything, so it might not be known.

https://cygwin.com/problems.html

**Comment by PiterGoCompany** [comment] 2017-10-06 05:58
There is new version of GIT that fixes the bug: [link](https://github.com/git-for-windows/git/releases/tag/v2.14.2.windows.2)

**Comment by rkeithhill** [comment] 2017-10-08 02:58
Considering this is not a bug in posh-git and the 2.14.2.windows.2 release fixes the issue, I'm going to close this.

**Closed by rkeithhill** 2017-10-08 02:58 UTC
