### ISSUE TITLE
DefaultPromptAbbreviateHomeDirectory not working when in ~

### ISSUE THREAD

**Issue by tig** [dahlbyk/posh-git#703] opened 2019-09-29 17:48 UTC
### System Details

- posh-git version/path: 1.0.0 beta3 ~\Documents\PowerShell\Modules\posh-git\1.0.0                                      - PowerShell version: 6.2.3
- git version 2.21.0.windows.1
- OS: Microsoft Windows NT 10.0.18362.0

### Issue Description

I can't get DefaultPromptAbbreviateHomeDirectory to work when I'm in the home director. See below. Suggestions?

![Gk53KPq 1](https://user-images.githubusercontent.com/585482/65836514-018d5980-e2a6-11e9-83d7-81e81129e1d1.png)

**Comment by rkeithhill** [comment] 2019-09-29 18:11
The way it is designed to work is to show the full path of your home if you are in your home dir but then collapse to `~\<sub-path>` once you are in a subdir of the home dir.  This was done to "cushion" the change for Windows users who are used to seeing their home dir path in the prompt.  

If you'd prefer a different impl, you can set the $GitPromptSettings.$DefaultPromptPath.Text to a interpolation string that returns the path the way you want it e.g.:
```
$GitPromptSettings.DefaultPromptPath.Text = '$(if ($pwd.Path.StartsWith($HOME, "OrdinalIgnoreCase")) { "~" + $pwd.Path.SubString($HOME.Length) } else { "$pwd" })'
```

**Comment by rkeithhill** [comment] 2019-10-16 04:18
@tig I'm closing this as `by design`. If you disagree, feel free to re-open the issue.

**Closed by rkeithhill** 2019-10-16 04:18 UTC
