### ISSUE TITLE
1.0.0-beta1 breaks compatibility with oh-my-posh

### ISSUE THREAD

**Issue by bergmeister** [dahlbyk/posh-git#539] opened 2018-01-21 13:50 UTC
### System Details

- posh-git version/path: 1.0.0-beta1 C:\Program Files\WindowsPowerShell\Modules\posh-git\1.0.0
- PowerShell version: 5.1.16299.98
- git version 2.15.0.windows.1
- OS: Microsoft Windows NT 10.0.16299.0

### Issue Description

Not sure if this is an issue with `posh-git` or [oh-my-posh](https://github.com/JanJoris/oh-my-posh) but version 1.0.0.-beta1 breaks compatibility with `oh-my-posh` whereby the prompt disappears and it can even hang. I know that 1.x contains breaking changes but this change was maybe not intended since `0.7.2-pre1` integrates without problems with `oh-my-posh`

**Comment by dahlbyk** [comment] 2018-01-21 15:06
I'm not surprised, as posh-git v1 changes quite a bit of our internals. We're trying pretty hard to keep v0 backwards-compatible.

cc @JanJoris

**Comment by dahlbyk** [comment] 2018-01-21 15:10
Do you see anything in `$Errors` or posh-git's captured [`$invokeErrors`](https://github.com/dahlbyk/posh-git/blob/bf0ec4ab3d35b36a26989916e5e1a270f7dc92a5/src/Utils.ps1#L4-L8)?

**Comment by JanJoris** [comment] 2018-01-21 18:06
I was trying to reproduce this on my current dev machine but PSCore doesn't seem to like v1 yet. I'll run a Windows dev setup asap to check what's going on.

**Comment by rkeithhill** [comment] 2018-01-21 23:44
If you are on PSCore, make sure you are running [PSReadLine 2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadline/2.0.0-beta1).

**Comment by rkeithhill** [comment] 2018-01-22 00:18
Also, the way `Write-GitStatus`, `Write-VcsStatus` and `Write-Prompt` are fundamentally different on a system that support ANSI esc seqs and has the property `$GitPromptSettings.AnsiConsole` set to $true.  @bergmeister if you set the above setting to $false, does posh-git / oh-my-posh behave any better?

@JanJoris The Write functions will not write anything if the host supports ANSI, they will instead return a string that contains ANSI esc sequences around text.  If the system doesn't support ANSI (or the user has disable ANSI support with the setting above), then the Write commands will write to host as before.  Here is the pattern we recommend:
```powershell
    $prompt = Write-Prompt "Text before posh-git prompt" -ForegroundColor Orange
    $prompt += & $GitPromptScriptBlock
    $prompt += Write-Prompt "Text after posh-git prompt" -ForegroundColor ([ConsoleColor]::Magenta)
    $prompt
```
In the ANSI not available (or disabled) case, $prompt will contain an empty string.

**Comment by bergmeister** [comment] 2018-01-22 00:48
@rkeithhill Thanks for the tip. Yes, setting `$GitPromptSettings.AnsiConsole = $false` does the trick. I think some themes stil have some artifacts but I might be wrong since I usually just use `Paradox` and therefore don't know the other themes too well.

**Comment by JanJoris** [comment] 2018-01-22 18:47
I was able to make the changes and everything works on PSCore. However, I still have to validate if this doesn't break the non-core version of PS. Pretty awesome though, no changes were needed to the logic in my scripts other than a few minor tweaks and @rkeithhill 's pointer towards `Write-Prompt`

![screenshot from 2018-01-22 19-47-07](https://user-images.githubusercontent.com/2492783/35238201-198d159e-ffad-11e7-91e9-177de385809f.png)

**Comment by rkeithhill** [comment] 2018-05-05 20:43
@JanDeDobbeleer Were you ever able to verify that the updated oh-my-posh works correctly on Windows PowerShell?

**Comment by JanDeDobbeleer** [comment] 2018-05-05 20:58
Please close the issue as everything seems to be working like a charm.

**Comment by rkeithhill** [comment] 2018-05-05 20:58
Excellent!

**Closed by rkeithhill** 2018-05-05 20:58 UTC

**Comment by bergmeister** [comment] 2018-05-05 21:55
Thanks, I can confirm this works now well with the latest version `2.0.0-beta1` of PSReadline and `1.0.0-beta1` of `posh-git` (and `2.0.193` of `oh-my-posh`) on Windows 10 1803 using `ConEmu 161206 [64] {Stable}`
