### ISSUE TITLE
Tab-completion works, but no status.

### ISSUE THREAD

**Issue by JoshMcCullough** [dahlbyk/posh-git#410] opened 2017-02-10 17:12 UTC
### System Details

- posh-git version: 0.6.1.20160330
- PowerShell version: 5.0.10240.17146
- git version 2.7.2.windows.1
- OS: Microsoft Windows NT 10.0.10240.0

### Issue Description

I've followed the README and checked the FAQ, but I can't get the status to show in the prompt. Tab-completion works fine, but no status for me! See the screenshot below, I can't even set `$GitPromptSettings.PromptSuffix`, and I'm not sure what I'm missing.

I've added things to my PS profile (all hosts), and it looks like this:

> Import-Module posh-git
> $GitPromptSettings.PromptSuffix = '`nPS$(''>'' * ($nestedPromptLevel + 1)) ' 
> $GitPromptSettings.PromptDebugSuffix = '`n[DBG]: PS$(''>'' * ($nestedPromptLevel + 1)) ' 

![image](https://cloud.githubusercontent.com/assets/4859660/22836274/b33cda88-ef89-11e6-9432-ebfa1bffcb27.png)

**Comment by rkeithhill** [comment] 2017-02-10 17:18
Duplicate of #409  TL;DR we haven't released 0.7.0 just yet.  Hopefully early next week.

**Closed by rkeithhill** 2017-02-10 17:18 UTC
