### ISSUE TITLE
[BUG] cursor on wrong place in powershell prompt

### ISSUE THREAD

**Issue by quchunguang** [dahlbyk/posh-git#280] opened 2016-04-29 23:22 UTC
``` bash
D:\repos\test [master ↑ +6 ~1 -0 !]> _ 
                                     ^ The cursor position initialize
D:\repos\test [master ↑ +6 ~1 -0 !]> abc_ 
                                        ^ The cursor position should be after some types
D:\repos\test [master ↑ +6 ~1 -0 !]> abc 
                                       ^ BUG: The cursor position NOW!
```

Test on Windows 10 64-bit Enterprise.

**Comment by dahlbyk** [comment] 2016-05-04 09:57
I've never seen this before, and I'm really not sure how it could be related to posh-git since we're not doing any cursor or direct host manipulation. Does anyone else experience this?

**Comment by xiaoxinw** [comment] 2016-07-08 03:39
Yeah, I have this issue now, on my laptop windows 10 64-bit.
But it have worked well before, it's weird.

**Comment by dahlbyk** [comment] 2016-07-17 21:13
What do you get from `$PSVersionTable.PSVersion`?

**Comment by xiaoxinw** [comment] 2016-07-25 01:56
5.0.10586.494   
But I didn't see this issue recently.

**Comment by dahlbyk** [comment] 2016-08-12 21:29
I'm going to go ahead and close this issue. Please reopen if you're able to reproduce.

**Closed by dahlbyk** 2016-08-12 21:29 UTC
