### ISSUE TITLE
cannot use start-sshagent

### ISSUE THREAD

**Issue by chantisnake** [dahlbyk/posh-git#253] opened 2016-02-03 23:31 UTC
![screenshot 21](https://cloud.githubusercontent.com/assets/10100995/12800526/b06e839e-caa3-11e5-95f7-1779a2c2eecb.png)

the many command including 
Get-SshAgent',
        'Start-SshAgent',
        'Stop-SshAgent',
        'Add-SshKey',
        'Get-SshPath',
does not work, I have reinstall this multiple times, and it haven't been fixed.

Any one have any idea why?

I encounter this problem when I find out the ssh-agent on my surface don't work(no prompt, it just cannot add private key), therefore I reinstalled it, and now there is error prompt on both of my computer(I sync powershell configuration, including profile and module via onedrive.)

**Comment by afscrome** [comment] 2016-02-09 20:40
This is caused by #242

**Comment by dahlbyk** [comment] 2016-06-30 19:20
This should be fixed now. Please reopen if you find that not to be the case.

**Closed by dahlbyk** 2016-06-30 19:20 UTC
