### ISSUE TITLE
Start-SshAgent Opens a command prompt and hangs the power shell

### ISSUE THREAD

**Issue by Abdullah2993** [dahlbyk/posh-git#270] opened 2016-03-18 18:17 UTC
My PowerShell Profile
```
import-module posh-git
function global:prompt {
    $realLASTEXITCODE = $LASTEXITCODE

    Write-Host($pwd.ProviderPath) -nonewline

    Write-VcsStatus

    $global:LASTEXITCODE = $realLASTEXITCODE
    return "> "
}

Pop-Location

Start-SshAgent -Quiet
```

> Start-SshAgent -Quiet
opens a command promp and hangs the powershell
![1](http://i.imgur.com/ILqfH4x.png)

**Comment by theaquamarine** [comment] 2016-03-18 18:37
What happens when you close the cmd window that appears?

**Comment by Abdullah2993** [comment] 2016-03-18 18:47
@theaquamarine nothing the command prompt closes but the PowerShell remains non-responsive

**Comment by Abdullah2993** [comment] 2016-03-18 18:50
@theaquamarine i think it has something to do with win32-openssh.
https://github.com/dahlbyk/posh-git/issues/258

**Comment by dahlbyk** [comment] 2016-03-20 23:23
Yeah, I'm going to go ahead and close this as a duplicate of #258. Keep an eye on https://github.com/PowerShell/Win32-OpenSSH/issues/110; in the meantime, the msys OpenSSH stuff has always worked well for me.

**Closed by dahlbyk** 2016-03-20 23:23 UTC

**Comment by dahlbyk** [comment] 2016-05-17 14:24
https://github.com/PowerShell/Win32-OpenSSH/issues/110#issuecomment-219603837:

> ssh-agent is reimplemented for Windows as a OS service. check out 5_15_2016 release details

**Comment by dahlbyk** [comment] 2016-06-30 19:21
Is anyone using Win32-OpenSSH able to take https://github.com/dahlbyk/posh-git/pull/295 for a spin to make sure it works as expected for you?
