### ISSUE TITLE
Duplicate prompt

### ISSUE THREAD

**Issue by felixfbecker** [dahlbyk/posh-git#486] opened 2017-09-27 17:38 UTC
### System Details

- posh-git version/path: 0.7.1
- PowerShell version:
```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      6.0.0-beta                                                                              
PSEdition                      Core                                                                                    
GitCommitId                    v6.0.0-beta.7                                                                           
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-37...
Platform                       Unix                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
WSManStackVersion              3.0  
```
- Git version: git version 2.13.5 (Apple Git-94)
- Operating system name and version: macOS Sierra 10.12.6 (16G29)

### Issue Description

My prompt is duplicated:
```ps
10:35 $ powershell 
PowerShell v6.0.0-beta.7
Copyright (C) Microsoft Corporation. All rights reserved.

/Users/felix/git/vscode [master ≡]> /Users/felix/git/vscode [master ≡]
```

further typing causes weird behavior:

![2017-09-27 10 36 53 am](https://user-images.githubusercontent.com/10532611/30928234-d8d55140-a36f-11e7-8dc7-2ae2d6e6ef66.gif)

**Comment by rkeithhill** [comment] 2017-09-27 18:22
Thanks for the bug report.  I can duplicate it on WSL/Bash.  I'll take a look at it.

**Comment by felixfbecker** [comment] 2017-09-27 18:30
Awesome, this is blocking me atm from using PowerShell as my primary terminal ❤️

**Comment by dahlbyk** [comment] 2017-09-27 20:07
> posh-git version/path: 0.7.1

How did you install posh-git? I would expect a different version number if you were using the `develop` branch, which has a few cross-platform fixes.

**Comment by felixfbecker** [comment] 2017-09-27 20:34
I followed the readme: `PowerShellGet\Install-Module posh-git -Scope CurrentUser`
I wanted to try the develop version but could not find any instructions on how to install that.

**Comment by dahlbyk** [comment] 2017-09-27 20:46
Unfortunately the PowerShell Gallery doesn't support prerelease versions yet.

> I wanted to try the develop version but could not find any instructions on how to install that.

This should do it:
```
cd wherever/you/want/it/installed
git clone https://github.com/dahlbyk/posh-git.git
git checkout develop
.\install.ps1
```

**Comment by felixfbecker** [comment] 2017-09-27 20:52
That gives me an error:
```
PS /Users/felix/git/posh-git> ./install.ps1                                                                             
Get-AuthenticodeSignature : The term 'Get-AuthenticodeSignature' is not recognized as the name of a cmdlet, function, s
cript file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is cor
rect and try again.
At /Users/felix/git/posh-git/src/Utils.ps1:163 char:16
+         $sig = Get-AuthenticodeSignature $profilePath
+                ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AuthenticodeSignature:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by felixfbecker** [comment] 2017-09-27 20:54
The prompt is not duplicated afterwards anymore, but the input is still weird:

![2017-09-27 1 53 53 pm](https://user-images.githubusercontent.com/10532611/30937363-5f9f7ff0-a38b-11e7-8ce4-f8d516e9dc63.gif)

**Comment by felixfbecker** [comment] 2017-09-27 20:54
I also noticed the added import to my profile uses backslashes:
```ps
Import-Module '/Users/felix/git/posh-git/src\posh-git.psd1'
```

**Comment by rkeithhill** [comment] 2017-09-27 22:01
Yeah, we have definitely have more work to do to finish up the cross-platform / PowerShell Core support.

**Comment by felixfbecker** [comment] 2017-09-27 23:40
Happy to test any fixes. Really want to get back to Powershell 💪

**Comment by rkeithhill** [comment] 2017-09-28 01:52
The issue is with PSReadline see - https://github.com/lzybkr/PSReadLine/issues/468.  There was a partial fix documented here - https://github.com/PowerShell/PowerShell/pull/3867.

The workaround for now is to add this line to your profile after the import of posh-git (develop branch) e.g.:
```
Import-Module $Home/GitHub/dahlbyk/posh-git/src/posh-git.psd1

$global:GitPromptSettings.DefaultPromptSuffix = "`n> "
```
The two keys are use esc seqs instead of `Write-Host` and for now, you can't have an esc seq on the line with the `>` char because PSReadline rewrites that char in a different color (red) to indicate syntax errors on the command line.

**Comment by rkeithhill** [comment] 2017-09-28 02:02
Also, found and fixed the `\` issue.  PR coming shortly.

**Comment by felixfbecker** [comment] 2017-09-28 02:05
That fixed it, thanks! Looking forward to a proper fix

![image](https://user-images.githubusercontent.com/10532611/30946093-cad3fd2a-a3b6-11e7-9204-9d38862bdf3e.png)

**Comment by lzybkr** [comment] 2017-09-28 04:58
The proper fix is sitting in this [branch](https://github.com/lzybkr/psreadline/tree/ansi_render) - it's at least preview quality, but I don't have custom key bindings working on Linux yet.

**Comment by rkeithhill** [comment] 2017-09-28 16:21
FWIW this workaround makes it tolerable on WSL/Bash on Windows 10.  There's still this weird cursor movement that happens as you type.  :-(

**Comment by dahlbyk** [comment] 2017-09-28 21:02
https://github.com/dahlbyk/posh-git/pull/487 has been merged into `develop` to fix Linux/macOS install issues.

**Comment by felixfbecker** [comment] 2017-09-28 21:07
Awesome to see the progress, keep it up :)

**Comment by binaryWard** [comment] 2017-11-22 15:04
When can the fix for this become available in the release?  I have been hoping the fix would be released sooner with how it impacts usage. I continue to see the problem.  
Using Mac OS 10.12.6 I just installed PowerShell 6.0.0-rc via brew.  Used install-module posh-git -scope CurrentUser.  
Result is the double prompt and odd behavior on input.

**Comment by lzybkr** [comment] 2017-11-22 15:37
The latest builds of PSReadLine address the double prompt and odd behavior on input, but installing requires replacing files in PowerShell 6.0.0-rc.

Hopefully that won't be necessary for the final release, but no guarantees, my free time doesn't necessarily line up with the PowerShell team's schedule.

**Comment by rkeithhill** [comment] 2017-11-23 17:52
@binaryWard If you clone this repo and checkout the develop branch and import the posh-git.psd1 file by its path, posh-git should work better on a Mac.  Also add this line to your profile after importing posh-git:
```
$global:GitPromptSettings.DefaultPromptSuffix = '`n$(''>'' * ($nestedPromptLevel + 1)) '
```
IIRC the current PSReadline impl behaves better if the prompt char `>` is on a line by itself.

**Comment by rkeithhill** [comment] 2017-12-31 07:09
I'm going to close this since the original issue is really a PSReadLine issue that has been fixed.  If you are running PS Core on Linux or macOS, you can install a beta of the 2.0.0 PSReadLine module with the following command:
```posh
Install-Module PSReadLine -RequiredVersion 2.0.0-Beta1 -AllowPrerelease -Scope CurrentUser
```

**Closed by rkeithhill** 2017-12-31 07:09 UTC
Labels: Area-PromptFunction, Bug

**Comment by felixfbecker** [comment] 2018-01-01 21:29
Getting this error when I'm trying to install it:
```
PS /Users/felix> Install-Module PSReadLine -RequiredVersion 2.0.0-Beta1 -AllowPrerelease -Scope CurrentUser             
Install-Module : Cannot process argument transformation on parameter 'RequiredVersion'. Cannot convert value "2.0.0-Beta1" to type "System.Version". Error: "Input string was not in a correct format."
At line:1 char:44
+ Install-Module PSReadLine -RequiredVersion 2.0.0-Beta1 -AllowPrerelea ...
+                                            ~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Install-Module], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,Install-Module
```

**Comment by rkeithhill** [comment] 2018-01-01 21:31
Sorry, we've not published Beta1 yet.  I was hoping you could try it from the GH source.  See the instructions I left in #501.

**Comment by felixfbecker** [comment] 2018-01-01 21:32
I don't see any instructions for PSReadline in #501?

**Comment by rkeithhill** [comment] 2018-01-01 21:34
Doh! Guess I should read these posts more thoroughly before replying.  You need to be on PS Core 6.0.0-rc2.  That is using a newer version of PowerShellGet (1.6.0) that understands the prerelease versioning.

**Comment by lzybkr** [comment] 2018-01-01 23:53
You can also just update (install) the latest PowerShellGet if you're running Windows PowerShell, probably something like `Install-Module -Force -AllowClobber -Scope CurrentUser PowerShellGet`.
