### ISSUE TITLE
posh-git.psm1 sets $Env:HOME, which screws with Emacs

### ISSUE THREAD

**Issue by mrcslws** [dahlbyk/posh-git#153] opened 2014-08-25 00:07 UTC
Emacs reads your `.emacs` from `%HOME%\.emacs`. Documentation: https://www.gnu.org/software/emacs/manual/html_node/emacs/Windows-HOME.html

If %HOME% isn't set, then it uses `%APPDATA%\.emacs`.

`posh-git.psm1` specifically sets `$Env:HOME`.

So using posh-git causes Emacs to suddenly start loading the `.emacs` from a different location, which is really confusing. It took a while before I tracked down why Emacs was misbehaving, and longer before I tracked the issue down to posh-git.

(Otherwise posh-git has been very helpful!)

**Comment by dahlbyk** [comment] 2015-05-14 14:55
Proposal:

1. If `git` resolves to `cmd\git.exe`, we're good.
1. If `git` resolves as `git.cmd`, set `%HOME%` and warn with suggestion to upgrade Git.
2. If `git` resolves as `bin\git.exe`, set `%HOME% and warn with suggestion to adjust `PATH` and/or aliases to check `cmd\` first.

**Comment by PetRose** [comment] 2015-08-25 09:51
I have a somewhat related problem, during the Chef Learning exercise (chef-dk) trying to set up Github Windows, on a fresh Win 8.1 (64bit), without Chocolatey (isn´t suggested during the install guidelines).
I get a "WARNING: git command could not be found. Please create an alias or add it to your PATH."
when I spin off a Git Shell from GIT. It seems theres several issues not being taken care of, during Github Windows install:
1) Powershell User profile, not being amended with proper Git settings:
 %HOMEDRIVE%%HOMEPATH%\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1
such as adding Git executables (or Command) to the %PATH% environment:
    %LOCALAPPDATA%\GitHub\shell.ps1
and possibly the Module path too. I can read the 'shell.ps1' saying a few of the commands inside this would not be needed to run manually, its taken care of during install. Obviously not for me.
2) The git executables (and commands) seems scattered across %LOCALAPPDATA% with weird foldernames (I a newbie, sure). The command 'dir C:\git.exe  /s' on root drive, gives me these (my substition of LOCALAPPDATA variable inserted)
  Directory of 
%LOCALAPPDATA%\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin
19-12-2014  05:57         1.503.744 git.exe
  Directory of
%LOCALAPPDATA%\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\cmd
19-12-2014  05:03             8.704 git.exe
  Directory of 
%LOCALAPPDATA%\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\libexec\git-core
19-12-2014  05:57         1.503.744 git.exe
and no one of these folders are set up in PATH (of PS Profile), hence the cause of my problem: Git command could not be found.

Should I raise another Issue item ? And in the meantime, which one of these should I add to my PS Profile ?

**Comment by dahlbyk** [comment] 2015-08-25 14:39
@PetRose GitHub for Windows only tries to set up its own "Git Shell" with its own `$PROFILE`; it doesn't (can't, perhaps?) touch your default `$PROFILE`. The "weird folder names" are an implementation detail that the team tries to hide from you to provide seamless Git & posh-git upgrades.

To mimic Git Shell in your default `$PROFILE`, add:

```powershell
# Load posh-git example profile
. (Resolve-Path "$env:LOCALAPPDATA\GitHub\shell.ps1")
. (Resolve-Path "$env:github_posh_git\profile.example.ps1")
```

@ammeep @shiftkey is there "official" guidance on usage of `shell.ps1` somewhere, or is it still "use at your own risk"?

**Comment by shiftkey** [comment] 2015-08-25 23:40
@dahlbyk it's very specific to GitHub Desktop, but if you reference it like that it should stay in sync as updates come down.

@PetRose GitHub Desktop doesn't change the user or system environment variables (in case you already have Git installed) and so all the heavy-lifting for setting up the environment is done through the Git Shell shortcut. If you really don't want to use Git Shell, I'd suggest @dahlbyk's workaround above.

Alternatively, you could install [Git for Windows](https://git-for-windows.github.io/) if you're only interested in having the command line tools available (that should address your original issue, and have the Git tools available at a known location).

**Comment by dahlbyk** [comment] 2017-01-06 09:15
I'm going to go ahead and close this since it doesn't seem to be an issue for the vast majority of users.

That said, I wouldn't be opposed to adding a note to the README about the module setting `$Env:HOME`.

**Closed by dahlbyk** 2017-01-06 09:15 UTC
Labels: Up-for-Grabs
