### ISSUE TITLE
Git Bash - Error in push command “CreateProcessW failed error:193”

### ISSUE THREAD

**Issue by PratikSoni2889** [dahlbyk/posh-git#728] opened 2019-12-13 06:51 UTC
### System Details

- posh-git version/path: Not installed
- PowerShell version: 5.1.17763.771
- Git version: 2.22.0.windows.1
- Operating system name and version: Microsoft Windows 10 Enterprise - 10.0.17763 N/A Build 17763

### Issue Description

I have been trying to execute some powershell script using Powershell ISE and for that I have been trying to add the SSH-Agent for that - on which I failed.

But when I tried to reset my old .ssh folder (I kept back of it before I started), it stopped working for my Git Bash and now I cannot push my changes to GitHub.

I have verified link1 but that's correct on my machine.

I have even checked my Environment Variables to make sure no unnecessary Git path set to that and that's on the correct side too.

Also, I have tried to push the branch by having the OpenSSH service in Start and Stop state.

Please let me know what check I missed here and how can I solve this issue.

**Comment by PratikSoni2889** [comment] 2019-12-13 08:52
@dahlbyk

**Comment by rkeithhill** [comment] 2019-12-13 22:25
I actually had a similar problem after a Windows update.  The `C:\WINDOWS\System32\OpenSSH` path got moved ahead of the later version I had installed in `C:\Program Files\OpenSSH-Win64`.  Get the latest openssh using Chocolatey `choco install openssh` and make sure that version is ahead of the Windows built-in version because the Choco version will be a later version.

**Comment by dahlbyk** [comment] 2020-03-14 04:00
I don't have anything to add beyond @rkeithhill's suggestion. Closing, as this seems to be an OpenSSH environment issue rather than something we can fix in posh-git or [posh-sshell](https://github.com/dahlbyk/posh-sshell).

**Closed by dahlbyk** 2020-03-14 04:00 UTC

**Comment by hanislovingit** [comment] 2021-05-13 00:35
I ran into the same error today. After some trial and error, I realized that the Windows Service OpenSSH Authentication Agent was set to Disabled for some reason. It could be due to the recent Windows update, but I'm not sure. I had to set the startup to Automatic and then I could start it running. Once it's running, my git commands were working again. Hopefully this will help someone

**Comment by rkeithhill** [comment] 2021-05-13 02:11
My experience has been that every single feature update (1903, 1909, 20H1, 20H2, etc) disables the service. You have to remember to start it and set it back to automatic start after each feature update:
```powershell
Get-Service ssh-agent | Set-Service -StartupType Automatic -PassThru | Start-Service
```

**Comment by hanislovingit** [comment] 2021-05-13 02:44
@rkeithhill thanks for the info. Good to know.

**Comment by Suheb786** [comment] 2024-07-03 11:12
If the SSH setup works fine in the terminal but not within an application or another context, it might be due to the application not picking up the correct SSH configuration or environment variables. Here are a few steps to troubleshoot and resolve this issue:

### Ensure Environment Variables Are Set Correctly

1. **Check SSH Agent is Running**:
   - Open Command Prompt and run:
     ```sh
     ssh-add -l
     ```
     This should list the SSH keys currently loaded by the SSH agent. If it shows an error, start the SSH agent and add the key again:
     ```sh
     start-ssh-agent.cmd
     ssh-add %userprofile%\.ssh\id_ed25519
     ```

### Configure SSH for the Application

1. **Configure Git to Use the Correct SSH Key**:
   - Ensure Git is configured to use the correct SSH key by setting the `GIT_SSH_COMMAND` environment variable.
   - Open Command Prompt and run:
     ```sh
     setx GIT_SSH_COMMAND "ssh -i %userprofile%\.ssh\id_ed25519"
     ```
     Or for `rsa`:
     ```sh
     setx GIT_SSH_COMMAND "ssh -i %userprofile%\.ssh\id_rsa"
     ```

### Check Application-Specific Settings

If you're using an Integrated Development Environment (IDE) or another application to interact with Git, ensure it is configured correctly:

1. **Visual Studio Code**:
   - Open the Command Palette (`Ctrl + Shift + P`).
   - Search for and select `Preferences: Open Settings (JSON)`.
   - Add or update the following configuration:
     ```json
     "git.path": "C:\\Program Files\\Git\\bin\\git.exe",
     "git.sshCommand": "ssh -i C:\\Users\\your_username\\.ssh\\id_ed25519"
     ```

2. **IntelliJ IDEA or Other JetBrains IDEs**:
   - Open `File` > `Settings`.
   - Navigate to `Version Control` > `Git`.
   - Set the `SSH executable` to `Native`.
   - Ensure the correct path to your SSH key is configured in your environment or use the `Native` SSH executable, which uses the system's SSH configuration.

### Use SSH Configuration File

1. **Create or Edit the SSH Config File**:
   - Open Command Prompt and run:
     ```sh
     notepad %userprofile%\.ssh\config
     ```
   - Add the following configuration:
     ```txt
     Host bitbucket.org
       HostName bitbucket.org
       User git
       IdentityFile ~/.ssh/id_ed25519
     ```
     Or for `rsa`:
     ```txt
     Host bitbucket.org
       HostName bitbucket.org
       User git
       IdentityFile ~/.ssh/id_rsa
     ```

### Final Steps

1. **Restart the Application**:
   - Close and reopen the application or IDE to ensure it picks up the new environment variables and SSH configuration.

2. **Retry the Git Command**:
   - Try running your Git command again within the application or IDE to see if the issue is resolved.

By following these steps, you should be able to ensure that your SSH key configuration is correctly picked up by the application or IDE you're using.
