### ISSUE TITLE
Cannot customize prompt, just shows "PS>"

### ISSUE THREAD

**Issue by piyushsoni** [dahlbyk/posh-git#693] opened 2019-09-03 05:06 UTC
### System Details

- posh-git version/path: v1.0
- PowerShell version: 5.1
- Git version: 2.17.1.windows.1
- Operating system name and version: Windows 10 Professional

### Issue Description

As soon as I installed posh-git, my prompt is actually changed from the usual directory listing to a simple "PS>", and whatever I do to customize the prompt according to [posh-git document](https://github.com/dahlbyk/posh-git#customizing-the-posh-git-prompt) , it has no effect. What can be wrong? 

Thanks,
Piyush Soni

**Comment by rkeithhill** [comment] 2019-09-03 13:07
Bring up a new PS console `powershell -noprofile` and run `import-module posh-git`.  Assuming you have the incorrect prompt `PS>`, copy the output of `$error[0]` to this issue.  Also, what is the value of `$GitPromptValues.LastPrompt`.

**Comment by SirKronos** [comment] 2019-09-19 22:19
I had the same problem with both the 1.0.0 beta 3 release and the master branch.

Following your instructions, I got the following output for `$error[0]`:

> Cannot add type. Compiling errors occurred.

(Original message on my language:"Não é possível adicionar o tipo. Ocorreram erros de compilação.")

I'm putting `$error[1]` here since it looks better for debugging:
```
Add-Type : Não é possível adicionar o tipo. Ocorreram erros de compilação.
No D:\Users\Kronos\Documents\WindowsPowerShell\posh-git-1.0.0-beta3\src\ConsoleMode.ps1:94 caractere:13
+             Add-Type $consoleModeSource
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand
```

**Comment by rkeithhill** [comment] 2019-09-19 23:23
What version of PowerShell are you using?  Run `$PSVersionTable` and post the output here.

**Comment by dahlbyk** [comment] 2019-09-19 23:37
@SirKronos Rather than `$error[1]`, can you share all of `$error`? I see something like this when I test a compile error locally:

```text
add-type : Cannot add type. Compilation errors occurred.
At line:1 char:1
+ add-type 'class {x}'
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand
 
add-type : c:\Users\Keith\AppData\Local\Temp\jvlaoo1q.0.cs(1) : Invalid token '}' in class, struct, or interface member declaration

c:\Users\Keith\AppData\Local\Temp\jvlaoo1q.0.cs(1) : >>> class {x}

At line:1 char:1
+ add-type 'class {x}'
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
 
add-type : c:\Users\Keith\AppData\Local\Temp\jvlaoo1q.0.cs(1) : Identifier expected

c:\Users\Keith\AppData\Local\Temp\jvlaoo1q.0.cs(1) : >>> class {x}

At line:1 char:1
+ add-type 'class {x}'
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
```

Seems like we might want to add a `try`/`catch` around the `Add-Type`, just in case.

**Comment by SirKronos** [comment] 2019-09-24 20:20
> @SirKronos What version of PowerShell are you using? Run `$PSVersionTable` and post the output here.

@rkeithhill This is  the output: 
```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

> @SirKronos Rather than `$error[1]`, can you share all of `$error`? I see something like this when I test a compile error locally:
> 
> ```
> add-type : Cannot add type. Compilation errors occurred.
> At line:1 char:1
> + add-type 'class {x}'
> + ~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
>     + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand
>  
> add-type : c:\Users\Keith\AppData\Local\Temp\jvlaoo1q.0.cs(1) : Invalid token '}' in class, struct, or interface member declaration
> 
> c:\Users\Keith\AppData\Local\Temp\jvlaoo1q.0.cs(1) : >>> class {x}
> 
> At line:1 char:1
> + add-type 'class {x}'
> + ~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
>     + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
>  
> add-type : c:\Users\Keith\AppData\Local\Temp\jvlaoo1q.0.cs(1) : Identifier expected
> 
> c:\Users\Keith\AppData\Local\Temp\jvlaoo1q.0.cs(1) : >>> class {x}
> 
> At line:1 char:1
> + add-type 'class {x}'
> + ~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Exception
>     + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
> ```
> 
> Seems like we might want to add a `try`/`catch` around the `Add-Type`, just in case.

@dahlbyk I thought about doing that before, but it seemed like a lot of redundancy to me. In any case, here's the full output of `$error`:

```
Não é possível adicionar o tipo. Ocorreram erros de compilação.
Add-Type : Não é possível adicionar o tipo. Ocorreram erros de compilação.
No D:\Users\Kronos\Documents\WindowsPowerShell\posh-git-1.0.0-beta3\src\ConsoleMode.ps1:94 caractere:13
+             Add-Type $consoleModeSource
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : (0) : Aviso como Erro: Caminho de pesquisa inválido 'C:\Program Files (x86)\Microsoft Visual
Studio\VC98\lib' especificado em 'variável de ambiente LIB' -- 'O sistema não pode encontrar o caminho especificado. '
(1) : using System;
No D:\Users\Kronos\Documents\WindowsPowerShell\posh-git-1.0.0-beta3\src\ConsoleMode.ps1:94 caractere:13
+             Add-Type $consoleModeSource
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Except
   ion
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : (0) : Aviso como Erro: Caminho de pesquisa inválido 'C:\Program Files (x86)\Microsoft Visual
Studio\VC98\mfc\lib' especificado em 'variável de ambiente LIB' -- 'O sistema não pode encontrar o caminho
especificado. '
(1) : using System;
No D:\Users\Kronos\Documents\WindowsPowerShell\posh-git-1.0.0-beta3\src\ConsoleMode.ps1:94 caractere:13
+             Add-Type $consoleModeSource
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Except
   ion
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Não é possível adicionar o tipo. Ocorreram erros de compilação.
Add-Type : Não é possível adicionar o tipo. Ocorreram erros de compilação.
No D:\Users\Kronos\Documents\WindowsPowerShell\posh-git-1.0.0-beta3\src\ConsoleMode.ps1:94 caractere:13
+             Add-Type $consoleModeSource
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : COMPILER_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : (0) : Aviso como Erro: Caminho de pesquisa inválido 'C:\Program Files (x86)\Microsoft Visual
Studio\VC98\lib' especificado em 'variável de ambiente LIB' -- 'O sistema não pode encontrar o caminho especificado. '
(1) : using System;
No D:\Users\Kronos\Documents\WindowsPowerShell\posh-git-1.0.0-beta3\src\ConsoleMode.ps1:94 caractere:13
+             Add-Type $consoleModeSource
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Except
   ion
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : (0) : Aviso como Erro: Caminho de pesquisa inválido 'C:\Program Files (x86)\Microsoft Visual
Studio\VC98\mfc\lib' especificado em 'variável de ambiente LIB' -- 'O sistema não pode encontrar o caminho
especificado. '
(1) : using System;
No D:\Users\Kronos\Documents\WindowsPowerShell\posh-git-1.0.0-beta3\src\ConsoleMode.ps1:94 caractere:13
+             Add-Type $consoleModeSource
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Except
   ion
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
```

**Comment by rkeithhill** [comment] 2019-09-24 20:26
It seems there is something about your `LIB` env var that is causing the "on-the-fly" compile to fail.  Try this:
```
powershell -noprofile
remove-item env:\lib
import-module posh-git -minimumVersion 1.0.0
```

**Comment by SirKronos** [comment] 2019-10-09 22:33
Finally got the time to test this, and it worked. I wonder what changed in 2 years that could have made this, though.

Right now, I've been using a version based on commit 9b6ee1c, and that error never happened. I'll try to pinpoint the cause later, but for now, I'll configure my profile to remove that env var until I notice any problem.

**Comment by rkeithhill** [comment] 2019-10-10 03:12
Thanks for the update.

**Comment by rkeithhill** [comment] 2019-11-23 01:38
@piyushsoni  I'm closing this since we haven't gotten any of the requested information. With that info, there is nothing for us to act on.  If you can provide that info, we can re-open this issue. The info we're looking for can be obtained by running `powershell -noprofile` and then `import-module posh-git` and then `$error`.  Copy the output of `$error` into this issue.

**Comment by rkeithhill** [comment] 2019-11-23 01:38
@piyushsoni  I'm closing this since we haven't gotten any of the requested information. With that info, there is nothing for us to act on.  If you can provide that info, we can re-open this issue. 

The info we're looking for can be obtained by running `powershell -noprofile` and then `import-module posh-git` and then `$error`.  Copy the output of `$error` into this issue.

**Closed by rkeithhill** 2019-11-23 01:38 UTC
